@BundlePay.Api_HostAddress = http://localhost:5192
@token =

GET {{BundlePay.Api_HostAddress}}/api/bundles
Accept: application/json



###

GET {{BundlePay.Api_HostAddress}}/api/services
Accept: application/json


###

POST {{BundlePay.Api_HostAddress}}/api/cart/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "bundleId": "0898687a-8cf1-4ed2-8b55-e75d2efd2e3b"
}


###

DELETE {{BundlePay.Api_HostAddress}}/api/cart/remove
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "bundleId": "00000000-0000-0000-0000-000000000001"
}


###

GET {{BundlePay.Api_HostAddress}}/api/cart
Accept: application/json
Authorization: Bearer {{token}}

